Repository star-whale/starwhale, pull requests merged in 2022-06, with the labels that each got.

#448 chore: separate homepage & docs just keep docs
  console/package.json
  console/public/index.html
  docs/docusaurus.config.js
  docs/package.json
  docs/src/components/selector/countries.js
  docs/src/components/selector/index.js
  docs/src/css/custom.css
  docs/src/css/custom.scss
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/src/theme/Footer/index.js
  docs/src/theme/Footer/index.scss
  docs/static/fonts/cousine-v25-latin-regular.eot
  docs/static/fonts/cousine-v25-latin-regular.svg
  docs/static/fonts/cousine-v25-latin-regular.ttf
  docs/static/fonts/cousine-v25-latin-regular.woff
  docs/static/fonts/cousine-v25-latin-regular.woff2
  docs/static/fonts/iconfont.css
  docs/static/fonts/iconfont.js
  docs/static/fonts/iconfont.json
  docs/static/fonts/iconfont.ttf
  docs/static/fonts/iconfont.woff
  docs/static/fonts/iconfont.woff2
  docs/static/fonts/project.svg
  docs/static/img/enterprise.svg
  docs/static/img/individuals.svg
  docs/static/img/intergrate_PyTorch.svg
  docs/static/img/line3-down.svg
  docs/static/img/line3-top.svg
  docs/static/img/line4-down.svg
  docs/static/img/line4-top.svg
  docs/static/img/line5-down.svg
  docs/static/img/line5-top.svg
  docs/static/img/success.svg
  docs/static/img/team.svg
  docs/yarn.lock
Labels: break-change

#445 Fix/optimis task action
  .github/workflows/server-build.yml
  .github/workflows/server-ut-report.yml
  server/Makefile
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/Action.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/TaskPool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/AbsBaseTaskAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Init2PreparingAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/MonitoringAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/AbsBaseCancelTaskAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Preparing2CanceledAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Running2CanceledAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/cancel/Uploading2CanceledAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/report/ReportAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/executor/TaskExecutor.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
  server/agent/src/main/resources/application.yaml
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
  server/controller/pom.xml
  server/controller/src/main/resources/application.yaml
Labels: optimize

#457 fix: raise exception for ppl/cmp handler
  client/starwhale/api/_impl/model.py
Labels: bug

#464 fix: lazylog ovelap/ new icon
  console/Makefile
  console/src/App.tsx
  console/src/assets/fonts/iconfont.css
  console/src/assets/fonts/iconfont.js
  console/src/assets/fonts/iconfont.json
  console/src/assets/fonts/iconfont.ttf
  console/src/assets/fonts/iconfont.woff
  console/src/assets/fonts/iconfont.woff2
  console/src/assets/fonts/setting.svg
  console/src/components/BaseSidebar.tsx
  console/src/components/Header/index.tsx
  console/src/components/IconFont/index.tsx
  console/src/pages/Job/JobTasks.tsx
Labels: bug

#469 extend the startup probe initialDelaySeconds
  docker/charts/templates/_helpers.tpl
  docker/charts/templates/controller-deployment.yaml
Labels: bug

#465 feat: add cmds for cloud mode
  client/starwhale/base/bundle.py
  client/starwhale/base/bundle_copy.py
  client/starwhale/base/cloud.py
  client/starwhale/base/view.py
  client/starwhale/core/dataset/cli.py
  client/starwhale/core/dataset/model.py
  client/starwhale/core/dataset/view.py
  client/starwhale/core/model/cli.py
  client/starwhale/core/model/model.py
  client/starwhale/core/model/view.py
  client/starwhale/core/runtime/model.py
  client/starwhale/core/runtime/view.py
  client/tests/core/test_dataset.py
  client/tests/core/test_model.py
  client/tests/core/test_runtime.py
Labels: feature

#471 bug: fix runtime copy existed typo
  client/starwhale/base/bundle_copy.py
Labels: bug

#473 feat: add gc/ui command
  client/starwhale/cli/mngt.py
  client/starwhale/mngt/__init__.py
  client/starwhale/utils/fs.py
  client/tests/core/test_mngt.py
Labels: feature

#485 Feat/agent support runtime
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/RuntimeManifest.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/TaskPersistence.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskDirTest.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
Labels: feature

#486 Uniform fields naming
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/SWDatasetInfoVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageInfoVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/user/RoleVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/user/RoleConvertor.java
Labels: refactor

#474 feat: add progress bar for copy
  client/starwhale/base/bundle_copy.py
  client/starwhale/base/cloud.py
Labels: feature, size/s

#492 fix runtime dir error
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
Labels: bug

#491 Recover model & dataset rest api
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageMapper.java
  server/controller/src/main/resources/mapper/SWDatasetMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageMapper.xml
Labels: enhancement

#493 add default base image;record image for task container
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
  docker/charts/templates/_helpers.tpl
  docker/charts/values.yaml
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/resources/application.yaml
Labels: feature

#494 fix: update runtime base image field
  client/starwhale/core/runtime/model.py
  example/mnist/requirements.txt
  example/mnist/runtime.yaml
Labels: bug

#495 yaml parse disable fail on unknown properties
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
Labels: bug

#496 fix runtime volume bug
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
Labels: bug

#497 feat: support .swignore for model/runtime ignore dirs
  client/starwhale/base/bundle.py
  client/starwhale/consts/__init__.py
  client/starwhale/core/dataset/model.py
  client/starwhale/core/model/model.py
  example/mnist/.swignore
  example/mnist/dataset.yaml
  example/mnist/model.yaml
Labels: feature

#498 fix result bug
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
Labels: bug

#500 fix: runtime build type typo
  client/starwhale/core/runtime/view.py
Labels: bug, size/s

#504 chores: update job cli for new controller api
  client/starwhale/base/view.py
  client/starwhale/core/job/model.py
  client/starwhale/core/job/view.py
Labels: enhancement, chores

#501 fix: get cloud info typo
  client/starwhale/base/cloud.py
  client/starwhale/core/project/model.py
Labels: bug, size/s

#507 optimise pull image way
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
Labels: bug

#508 chores: update info output
  client/starwhale/core/job/view.py
Labels: chores, size/s

#509 fix task persistent, job list bug
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusChangeWatcher.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForPersist.java
Labels: bug

#512 volume pip cache dir for task container
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: feature

#510 enhance: add pip cache dir for standalone job
  client/scripts/sw-docker-entrypoint
  client/starwhale/consts/__init__.py
  client/starwhale/core/job/executor.py
  client/starwhale/utils/venv.py
  client/tests/core/test_executor.py
Labels: enhancement

#516 enhance：add version for starwhale local config.yaml
  client/starwhale/consts/__init__.py
  client/starwhale/utils/config.py
  client/tests/data/config.yaml
Labels: enhancement

#515 support include-editable for runtime build
  client/starwhale/core/runtime/cli.py
  client/starwhale/core/runtime/model.py
  client/starwhale/core/runtime/view.py
  client/starwhale/utils/venv.py
  client/tests/core/test_runtime.py
Labels: feature

#506 Runtime push force & head dataset api
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/ClientRuntimeRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
  server/controller/src/main/resources/mapper/SWDatasetMapper.xml
Labels: enhancement

#524 fix: handle not found instance and project
  client/starwhale/utils/config.py
  client/tests/utils/test_config.py
Labels: bug

#527 feat: dag with job/dag api
  console/package.json
  console/src/components/DAG/DAG.tsx
  console/src/components/DAG/index.scss
  console/src/components/IconFont/index.tsx
  console/src/domain/job/schemas/job.tsx
  console/src/domain/job/services/job.ts
  console/src/i18n/locales.ts
  console/src/pages/Job/JobDAG.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobOverviewLayout.tsx
  console/src/pages/Job/TaskListCard.tsx
  console/src/routes.tsx
  console/yarn.lock
Labels: feature

#530 enhance: use virtualvenv for venv_setup
  client/starwhale/utils/venv.py
  client/tests/core/test_runtime.py
Labels: enhancement

#521 feat: add runtime activate cmd
  client/starwhale/core/runtime/cli.py
  client/starwhale/core/runtime/model.py
  client/starwhale/core/runtime/view.py
  client/starwhale/utils/venv.py
Labels: feature

#532 hotfix:graceful to handle pip cache
  client/scripts/sw-docker-entrypoint
  client/starwhale/utils/venv.py
Labels: hotfix

#526 api: Runtime & Model manifest
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/ClientRuntimeRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeInfoVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/runtime/RuntimeVersionVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageInfoVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageVersionEntity.java
  server/controller/src/main/resources/db/migration/V00012__add_manifest.sql
  server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
Labels: enhancement

#533 WIP: chores: upgrade base image to 0.2.0 for pip upgrade
  docker/Dockerfile.base
  docker/Makefile
Labels: chores

#535 fix: remove logger catch for executor run
  client/starwhale/core/job/executor.py
Labels: bug

#538 add model size field into model version api
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StorageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
Labels: enhancement

#544 fix pip cache dir bug
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: bug

#546 update: runtime icon/job relative fields
  console/src/assets/fonts/iconfont.css
  console/src/assets/fonts/iconfont.json
  console/src/assets/fonts/iconfont.ttf
  console/src/assets/fonts/iconfont.woff
  console/src/assets/fonts/iconfont.woff2
  console/src/components/IconFont/index.tsx
  console/src/components/Table/TableTyped.tsx
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/job/schemas/job.tsx
  console/src/hooks/window/useResizeObserver.ts
  console/src/pages/Project/ProjectSidebar.tsx
Labels: break-change

#543 chores: update cli job create parameter name
  client/starwhale/core/job/model.py
Labels: chores, size/s

#547 add log for agent at stage of preparing and running
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/AbsBaseTaskAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/MonitoringAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemPath.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/TaskPersistence.java
Labels: feature

#548 Feat/optimise log while preparing
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: optimize

#558 fix: slove model build copy fs unexpected issue
  client/starwhale/base/bundle.py
  client/starwhale/base/store.py
  client/starwhale/core/job/model.py
  client/starwhale/core/model/model.py
  client/starwhale/core/runtime/store.py
  client/tests/core/test_job.py
Labels: bug, standalone, client

#545 enhance: add runtime validator
  client/setup.py
  client/starwhale/core/runtime/model.py
  client/starwhale/utils/venv.py
Labels: enhancement, standalone, client

#564 example support 2.0
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: bug

#563 add/remove/search tag for model/dataset/runtime
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/common/TagAction.java
  server/controller/src/main/java/ai/starwhale/mlops/common/util/TagUtil.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageVersionEntity.java
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
Labels: enhancement

#565 allow failed job be resumed
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/HotJobsLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/cache/JobLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
Labels: enhancement

#568 enhance: smart import user venv/conda sys.path
  client/starwhale/utils/error.py
  client/starwhale/utils/load.py
  client/starwhale/utils/venv.py
  client/tests/utils/test_load.py
Labels: enhancement, standalone, client

#570 enhance: runtime refactor for create
  client/starwhale/consts/__init__.py
  client/starwhale/core/runtime/cli.py
  client/starwhale/core/runtime/model.py
  client/starwhale/core/runtime/view.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/venv.py
  client/tests/core/test_runtime.py
  docker/Makefile
Labels: enhancement, size/l, standalone, client

#574 enhance: allow project empty for swcli job create
  client/starwhale/core/job/cli.py
  client/tests/base/test_uri.py
Labels: enhancement, standalone, client

#577 bug: update conda activate text for host environment
  client/starwhale/utils/venv.py
  docker/Dockerfile.starwhale
Labels: bug, standalone, client

#575 enhance: auto pip install user pip-req file in conda restore process
  client/starwhale/core/runtime/model.py
  client/starwhale/utils/venv.py
  client/tests/core/test_runtime.py
Labels: enhancement, standalone, client

#573 enhance: tune runtime/model remove workdir
  client/starwhale/base/store.py
  client/starwhale/core/model/model.py
  client/starwhale/core/model/store.py
  client/starwhale/core/runtime/model.py
  client/starwhale/core/runtime/store.py
  client/starwhale/mngt/__init__.py
  client/tests/core/test_mngt.py
  client/tests/core/test_runtime.py
Labels: enhancement, standalone, client

#585 hotfix: fix python verion for virtualenv
  client/starwhale/utils/venv.py
Labels: hotfix, standalone, client, runtime

#580 Allow models/runtimes/datasets with the same name for different projects
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SwdsManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageMapper.java
  server/controller/src/main/resources/mapper/RuntimeMapper.xml
  server/controller/src/main/resources/mapper/SWDatasetMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageMapper.xml
Labels: bug, enhancement

#591 feat: new ui for doc homepage
  docs/src/css/custom.scss
  docs/src/pages/index.js
  docs/src/pages/index.scss
  docs/src/pages/styles.module.css
  docs/static/img/banner-1920x1080.jpg
  docs/static/img/banner-2560x1440.jpg
  docs/static/img/banner-3840x2160.jpg
Labels: enhancement

#592 Delete baseImage & Merge sql
  server/controller/src/main/java/ai/starwhale/mlops/api/EnvApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/EnvService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/BaseImageMapper.java
  server/controller/src/main/resources/db/migration/V00001__Create_schema.sql
  server/controller/src/main/resources/db/migration/V00002__Add_data.sql
  server/controller/src/main/resources/db/migration/V00003__modify_agent.sql
  server/controller/src/main/resources/db/migration/V00004__add_agent_status.sql
  server/controller/src/main/resources/db/migration/V00005__add_job_comment.sql
  server/controller/src/main/resources/db/migration/V00006__add_dag.sql
  server/controller/src/main/resources/db/migration/V00007__add_job_deleted.sql
  server/controller/src/main/resources/db/migration/V00008__add_runtime.sql
  server/controller/src/main/resources/db/migration/V00009__add_step.sql
  server/controller/src/main/resources/db/migration/V00010__modify_job.sql
  server/controller/src/main/resources/db/migration/V00011__add_time_to_task_step.sql
  server/controller/src/main/resources/db/migration/V00012__add_manifest.sql
  server/controller/src/main/resources/mapper/BaseImageMapper.xml
Labels: refactor

#598 fix: standalone job data_loader load first line record twice
  client/starwhale/core/job/executor.py
  client/starwhale/utils/debug.py
Labels: bug, standalone

#597 fix: modify project api support project url
  server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
Labels: bug, enhancement

#593 chores: add cname for gh-pages action
  .github/workflows/docs.yaml
Labels: doc, chores, ci

#600 add unit test for localDateTImeConvertor
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentConverter.java
  server/controller/src/test/java/ai/starwhale/test/ObjectMockHolder.java
  server/controller/src/test/java/ai/starwhale/test/common/LocalDateTimeConvertorTest.java
  server/controller/src/test/java/ai/starwhale/test/domain/system/AgentCacheTest.java
Labels: unit test

#603 feat: support run eval job in standalone instance without docker
  README.md
  client/starwhale/api/_impl/model.py
  client/starwhale/core/dataset/cli.py
  client/starwhale/core/job/cli.py
  client/starwhale/core/job/executor.py
  client/starwhale/core/job/model.py
  client/starwhale/core/job/view.py
  client/starwhale/core/model/cli.py
  client/starwhale/utils/error.py
  client/starwhale/utils/progress.py
  client/starwhale/utils/venv.py
  client/tests/core/test_executor.py
  docs/docs/quickstart/standalone.md
Labels: feature, standalone, client

#606 feat(client): job compare in standalone mode
  client/starwhale/core/job/cli.py
  client/starwhale/core/job/model.py
  client/starwhale/core/job/view.py
Labels: feature, standalone, client

#610 chores(environment): test and update doc for mac
  README.md
  client/starwhale/core/job/executor.py
  docs/docs/quickstart/standalone.md
  docs/docs/standalone/installation.md
Labels: doc, chores, standalone

#614 Feat/add nexus for ansible
  bootstrap/README.md
  bootstrap/setup.py
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/bootstrap.yaml
  bootstrap/starwhale_bootstrap/playbook/hosts
  bootstrap/starwhale_bootstrap/playbook/roles/minio/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/nexus/tasks/main.yaml
  docker/charts/Chart.lock
  docker/charts/Chart.yaml
  docker/charts/charts/common-1.13.0.tgz
  docker/charts/charts/common-1.16.0.tgz
  docker/charts/charts/minio-11.2.13.tgz
  docker/charts/charts/minio-11.7.6.tgz
  docker/charts/charts/mysql-8.9.2.tgz
  docker/charts/charts/mysql-8.9.6.tgz
  docker/charts/charts/nexus-repository-manager-39.0.0.tgz
  docker/charts/templates/NOTES.txt
  docker/charts/values.yaml
Labels: feature

#613 add audio classification example
  example/speech_command/README.md
  example/speech_command/__init__.py
  example/speech_command/code/__init__.py
  example/speech_command/code/data_slicer.py
  example/speech_command/code/dataset.py
  example/speech_command/code/model.py
  example/speech_command/code/ppl.py
  example/speech_command/code/predict.py
  example/speech_command/code/train.py
  example/speech_command/dataset.yaml
  example/speech_command/doc/img.png
  example/speech_command/model.yaml
  example/speech_command/requirements.txt
Labels: example

#612 ci(client): add ut for sdk and client
  client/.coveragerc
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/starwhale/core/dataset/model.py
  client/starwhale/core/model/model.py
  client/tests/data/dataset/mnist/data
  client/tests/data/dataset/mnist/label
  client/tests/data/dataset/swds/data_ubyte_0.swds_bin
  client/tests/data/dataset/swds/index.jsonl
  client/tests/data/dataset/swds/label_ubyte_0.swds_bin
  client/tests/sdk/__init__.py
  client/tests/sdk/test_dataset.py
  client/tests/sdk/test_metric.py
  client/tests/sdk/test_model.py
  example/mnist/mnist/process.py
Labels: ci, standalone, sdk, client

#616 hotfix(client): remove pdb typo
  client/starwhale/api/_impl/loader.py
Labels: hotfix, standalone

#615 RestAPI & Service & Mapper & Objects for Evaluation
  server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/AttributeVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/AttributeValueVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/ConfigRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/ConfigVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/SummaryVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/ViewConfigConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/bo/ConfigQuery.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/bo/SummaryFilter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/mapper/ViewConfigMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/po/ViewConfigEntity.java
  server/controller/src/main/resources/config/evaluation_attributes
  server/controller/src/main/resources/db/migration/V00003__Add_view_config.sql
  server/controller/src/main/resources/mapper/ViewConfigMapper.xml
Labels: enhancement, feature

#618 fix agent log upload error
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Uploading2FinishedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/report/ReportAction.java
Labels: bug

#627 fix(console): data-table full columns missing in cases
  console/src/components/Table/TableTyped.tsx
  console/src/components/data-table/column.tsx
  console/src/components/data-table/data-custom-table.tsx
  console/src/components/data-table/stateful-data-table.tsx
  console/src/components/data-table/types.tsx
Labels: hotfix, size/s, javascript

#626 Simple implementation of Evaluation Summary list
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/EvaluationController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/ConfigRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
  server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java
  server/pom.xml
Labels: enhancement

#630 example: refine for ped detection & audio cls example
  client/tests/utils/test_process.py
  example/PennFudanPed/README.md
  example/PennFudanPed/code/coco_eval.py
  example/PennFudanPed/code/coco_utils.py
  example/PennFudanPed/code/data_slicer.py
  example/PennFudanPed/code/engine.py
  example/PennFudanPed/code/ppl.py
  example/PennFudanPed/doc/img.png
  example/PennFudanPed/model.yaml
  example/PennFudanPed/requirements.txt
  example/PennFudanPed/runtime.yaml
  example/speech_command/README.md
Labels: example

#636 enhance(console) eva compare table
  console/src/components/DnD/DnDContainer.tsx
  console/src/components/Table/TableTyped.tsx
  console/src/components/data-table/column-string.tsx
  console/src/components/data-table/config-manage-columns.tsx
  console/src/components/data-table/data-custom-table.tsx
  console/src/components/data-table/measure-column-widths.tsx
  console/src/components/data-table/stateful-data-table.tsx
  console/src/components/data-table/types.tsx
  console/src/consts/index.ts
  console/src/hooks/global.ts
  console/src/hooks/useDrawer.ts
  console/src/hooks/useSelection.ts
  console/src/i18n/locales.ts
  console/src/pages/Evaluation/EvaluationListCard.tsx
  console/src/pages/Evaluation/EvaluationListCompare.tsx
  console/src/pages/Runtime/RuntimeVersionListCard.tsx
Labels: enhancement, size/m

#637 doc: add on premises doc
  docs/docs/img/create-job-workflow.gif
  docs/docs/img/ui-create-job.jpg
  docs/docs/img/ui-job-results.jpg
  docs/docs/img/ui-job-steps.jpg
  docs/docs/img/ui-list-dataset.jpg
  docs/docs/img/ui-list-model.jpg
  docs/docs/img/ui-list-project.jpg
  docs/docs/img/ui-list-runtime.jpg
  docs/docs/quickstart/on-premises.md
Labels: doc

#638 doc: fix on premises doc hyper link error
  docs/docs/quickstart/on-premises.md
Labels: doc

#631 feat(sdk): support serialize and deserialize in PipelineHandler
  client/requirements-dev.txt
  client/setup.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/tests/sdk/test_model.py
  example/PennFudanPed/code/ppl.py
  example/cifar10/code/ppl.py
  example/mnist/mnist/ppl.py
  example/nmt/code/ppl.py
  example/speech_command/code/ppl.py
  example/text_cls_AG_NEWS/code/ppl.py
Labels: enhancement, sdk

#639 fix(console): pined column state error
  console/src/hooks/useSelection.ts
Labels: hotfix

#634 bug(controller):fix bugs in dataset api
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/RuntimeApi.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSVersionConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
Labels: bug

#641 mount ui from external dir
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  docker/charts/templates/controller-deployment.yaml
  server/controller/src/main/resources/application.yaml
Labels: feature

#645 chores(helm): add private registry for pre deploy
  .github/workflows/release.yml
Labels: enhancement

#646 only mount ui dir
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  docker/charts/templates/controller-deployment.yaml
Labels: bug

#629 WIP: doc(standalone): add overview for cli doc
  client/starwhale/base/bundle_copy.py
  client/starwhale/cli/__init__.py
  client/starwhale/cli/mngt.py
  client/starwhale/core/dataset/cli.py
  client/starwhale/core/dataset/view.py
  client/starwhale/core/instance/cli.py
  client/starwhale/core/instance/view.py
  client/starwhale/core/job/cli.py
  client/starwhale/core/model/cli.py
  client/starwhale/core/model/view.py
  client/starwhale/core/project/cli.py
  client/starwhale/core/runtime/cli.py
  client/starwhale/core/runtime/view.py
  client/tests/base/test_copy.py
  docs/docs/reference/cli/dataset.md
  docs/docs/reference/cli/instance.md
  docs/docs/reference/cli/job.md
  docs/docs/reference/cli/main.md
  docs/docs/reference/cli/model.md
  docs/docs/reference/cli/other.md
  docs/docs/reference/cli/project.md
  docs/docs/reference/cli/runtime.md
  docs/docs/standalone/client_user_guide.md
  docs/sidebars.js
Labels: doc, standalone

#648 * Evaluation list format judgement
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/evaluation/SummaryVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
  server/controller/src/main/resources/config/evaluation_attributes
  server/controller/src/main/resources/mapper/JobMapper.xml
  server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java
Labels: bug, enhancement

#647 fix issue 633 :response to FE with readable error when uerying dag of job at status of created
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
  server/controller/src/test/java/ai/starwhale/test/domain/dag/DAGQuerierTest.java
Labels: bug

#650 Fix: agent log with line separator
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
Labels: bug

#649 doc(standalone): add standalone doc for project/instance/job
  client/starwhale/cli/mngt.py
  client/starwhale/core/dataset/cli.py
  client/starwhale/core/job/cli.py
  client/starwhale/core/job/view.py
  client/starwhale/core/project/cli.py
  client/starwhale/core/project/model.py
  client/starwhale/core/project/view.py
  docs/docs/quickstart/standalone.md
  docs/docs/reference/cli/dataset.md
  docs/docs/reference/cli/instance.md
  docs/docs/reference/cli/job.md
  docs/docs/reference/cli/model.md
  docs/docs/reference/cli/other.md
  docs/docs/reference/cli/project.md
  docs/docs/reference/cli/runtime.md
  docs/docs/reference/cli/utilities.md
  docs/docs/standalone/client_user_guide.md
  docs/sidebars.js
Labels: doc 📄, standalone 💻

#652 chores(client): update object name validation
  client/starwhale/utils/__init__.py
  client/tests/utils/test_common.py
Labels: chores 🛎️, client 🌈

#653 deploy(cloud): cloud instance docker compose
  client/scripts/sw-docker-entrypoint
  docker/compose/README.md
  docker/compose/compose.override.yaml
  docker/compose/compose.yaml
Labels: feature ✨, deploy 🚀, cloud ☁️

#654 feat:add new env for docker
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/resources/application.yaml
Labels: enhancement ❤️

#655 chores(docker): update disable debug env name
  client/scripts/sw-docker-entrypoint
Labels: chores 🛎️, docker

#651 fix(deploy): tune jvm heap size
  docker/Dockerfile.server
  docker/charts/templates/_helpers.tpl
  docker/charts/templates/controller-deployment.yaml
Labels: bug 🐛

#656 bug(docker): fix pip cache config error in sw-docker-entrypoint
  client/scripts/sw-docker-entrypoint
Labels: bug 🐛, docker 🗃️

#657 bug(docker): fix trusted host in default pip config
  docker/external/pip.conf
Labels: docker 🗃️

#658 Evaluation list: only return the summary in attributes
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
  server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java
Labels: enhancement ❤️

#659 bug(client): fix project select error
  client/starwhale/base/uri.py
  client/starwhale/core/project/view.py
  client/tests/core/test_project.py
  client/tests/data/config.yaml
  client/tests/utils/test_config.py
Labels: bug 🐛, standalone 💻, client 🌈

#663 fix(agent): extension pull image time; add preparing status for report
  bootstrap/setup.py
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
  docker/charts/templates/_helpers.tpl
  docker/charts/values.yaml
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
  server/agent/src/main/resources/application.yaml
Labels: bug 🐛

#661 fix(bootstrap): change ansible storage image
  bootstrap/README.md
  bootstrap/setup.py
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/deploy.py
  bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/minio/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/mysql/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/nexus/tasks/main.yaml
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
  server/agent/src/main/resources/application.yaml
Labels: bug 🐛

#666 bug(helm): fixchart env value parse error
  docker/charts/templates/_helpers.tpl
Labels: bug 🐛, standalone 💻, deploy 🚀

#667 bug(sdk): fix s3 data loader type
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/tests/utils/test_process.py
Labels: bug 🐛, sdk 🐶

#664 feat(client): dataset cmd of swcli support output to json
  client/starwhale/base/view.py
  client/starwhale/cli/__init__.py
  client/starwhale/core/dataset/cli.py
  client/starwhale/core/dataset/view.py
Labels: client 🌈

#669 fix(deploy): change chart number to string
  docker/charts/values.yaml
Labels: bug 🐛

#665 chores(deploy): update compose image version and pypi mirrors
  docker/compose/compose.override.yaml
  docker/compose/compose.yaml
Labels: chores 🛎️, docker 🗃️, deploy 🚀, cloud ☁️

#671 doc(standalone): add standalone runtime and overview guides doc
  client/starwhale/core/runtime/model.py
  docs/docs/standalone/client_user_guide.md
  docs/docs/standalone/configuration.md
  docs/docs/standalone/dataset.md
  docs/docs/standalone/evaluation.md
  docs/docs/standalone/installation.md
  docs/docs/standalone/main.md
  docs/docs/standalone/model.md
  docs/docs/standalone/overview.md
  docs/docs/standalone/runtime.md
  docs/sidebars.js
Labels: doc 📄, standalone 💻

#677 bug(controller): evaluation list cache
  server/controller/src/main/java/ai/starwhale/mlops/domain/evaluation/EvaluationService.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultQuerier.java
  server/controller/src/test/java/ai/starwhale/test/resulting/ResultQuerierTest.java
Labels: bug 🐛

#676 feat(client): runtime cmd of swcli support output to json
  client/starwhale/core/runtime/cli.py
  client/starwhale/core/runtime/view.py
Labels: feature ✨, client 🌈

#678 feat(client): job cmd of swcli support output to json
  client/starwhale/core/job/cli.py
  client/starwhale/core/job/view.py
  client/tests/core/test_job.py
Labels: client 🌈

#680 doc(example): add example doc
  docs/docs/img/cifar10_create.png
  docs/docs/img/cifar10_result1.png
  docs/docs/img/cifar10_result2.png
  docs/docs/img/cifar10_result3.png
  docs/docs/img/cifar10_result4.png
  docs/docs/img/create_job_ag_news.png
  docs/docs/tutorials/ag_news.md
  docs/docs/tutorials/cifar10.md
  docs/docs/tutorials/main.md
  docs/docs/tutorials/mnist.md
  docs/docs/tutorials/pfp.md
  docs/docs/tutorials/speech.md
  docs/sidebars.js
  example/PennFudanPed/READMD.md
  example/PennFudanPed/doc/img.png
  example/cifar10/READMD.md
  example/mnist/README.md
  example/speech_command/README.md
  example/speech_command/doc/img.png
  example/text_cls_AG_NEWS/README.md
Labels: doc 📄, example 🚕

#684 doc: remove some dead links
  README.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: doc 📄, typo 🆎

#685 doc(standalone): add standalone model/runtime guide docs
  docs/docs/standalone/dataset.md
  docs/docs/standalone/model.md
  docs/docs/standalone/runtime.md
  docs/sidebars.js
Labels: doc 📄

#683 feat(standalone): end to end test for client
  .github/file-filter.yml
  .github/workflows/client.yaml
  scripts/run_demo.sh
Labels: ci 🕹️, standalone 💻, client 🌈

#688 doc: refine docs
  docs/docs/cloud/helm-charts.md
  docs/docs/quickstart/on-premises.md
  docs/docs/quickstart/standalone.md
  docs/docs/reference/cli/dataset.md
  docs/docs/reference/cli/instance.md
  docs/docs/reference/cli/job.md
  docs/docs/reference/cli/main.md
  docs/docs/reference/cli/model.md
  docs/docs/reference/cli/project.md
  docs/docs/reference/cli/runtime.md
  docs/docs/reference/cli/utilities.md
  docs/docs/standalone/installation.md
  docs/docs/standalone/overview.md
  docs/docs/standalone/runtime.md
Labels: doc 📄

#690 fix(client): make targets phony
  client/Makefile
Labels: client 🌈

#689 fix(client): do not set default project for cloud instance
  client/starwhale/core/job/model.py
  client/starwhale/utils/config.py
Labels: bug 🐛, client 🌈

#692 feat(console): support evaluation summary metrics
  console/package.json
  console/src/__generated__/MySuperbApi.ts
  console/src/components/Header/Logo.tsx
  console/src/components/Table/TableTyped.tsx
  console/src/components/data-table/column-numerical.tsx
  console/src/components/data-table/config-manage-columns.tsx
  console/src/components/data-table/header-cell.tsx
  console/src/components/data-table/stateful-data-table.tsx
  console/src/domain/evaluation/hooks/useFetchEvaluationAttrs.ts
  console/src/domain/evaluation/hooks/useFetchEvaluations.ts
  console/src/domain/evaluation/schemas/evaluation.tsx
  console/src/domain/evaluation/services/evaluation.ts
  console/src/i18n/locales.ts
  console/src/pages/Evaluation/EvaluationListCard.tsx
  console/src/pages/Evaluation/EvaluationListCompare.tsx
  console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
  console/src/pages/Job/JobTasks.tsx
  console/src/pages/Project/ProjectSidebar.tsx
  console/src/routes.tsx
  console/src/styles/_global.scss
  console/swagger.js
  console/swagger.json
  console/yarn.lock
Labels: enhancement ❤️, size/m 🦌

#693 ci(github): add wip config
  .github/wip.yaml
Labels: ci 🕹️

#695 chore(console): update fied name and css shorthand
  console/src/components/BaseSidebar.tsx
  console/src/components/Button/Button.tsx
  console/src/components/Card/index.tsx
  console/src/components/Table/TableTyped.tsx
  console/src/components/Table/index.tsx
  console/src/components/data-table/data-custom-table.tsx
  console/src/components/data-table/data-table.tsx
  console/src/components/data-table/header-cell.tsx
  console/src/i18n/locales.ts
  console/src/pages/Dataset/Overview.tsx
  console/src/pages/Evaluation/EvaluationListCard.tsx
  console/src/pages/Evaluation/EvaluationListCompare.tsx
  console/src/pages/Evaluation/EvaluationOverviewLayout.tsx
  console/src/pages/Evaluation/EvaluationResults.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobOverviewLayout.tsx
  console/src/pages/Job/JobResults.tsx
  console/src/pages/Model/Overview.tsx
  console/src/pages/Runtime/Overview.tsx
Labels: chores 🛎️, size/s 🐀

#696 bug(doc): fix docs title and remove useless notes
  docs/docusaurus.config.js
  docs/src/pages/index.js
Labels: bug 🐛, doc 📄

#687 refactor(controller):Extract the same Tag/Revert/Recover business code of Model/Dataset/Runtime
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleException.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleURL.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleVersionAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/BundleVersionURL.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/DeletedBundleAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/BundleEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/BundleVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/HasId.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/base/HasName.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/recover/RecoverAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/recover/RecoverException.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/recover/RecoverManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/revert/RevertAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/revert/RevertManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/HasTag.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/HasTagWrapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagException.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/bundle/tag/TagManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectAccessor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/RuntimeService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/mapper/RuntimeVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/runtime/po/RuntimeVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SwdsManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/po/SWDatasetEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/po/SWDatasetVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SwmpManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/po/SWModelPackageEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/po/SWModelPackageVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
  server/controller/src/main/resources/mapper/RuntimeVersionMapper.xml
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
Labels: refactor 🐛
