Repository star-whale/starwhale, pull requests merged in 2022-04, with the labels that each got.

#47 decouple controller task bo from agent
  server/agent/src/main/java/ai/starwhale/mlops/agent/report/ReportHttpClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/cancel/AbsBaseCancelTaskTransition.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/FinishedOrCanceled2ArchivedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Init2PreparingAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/executor/TaskExecutor.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/ReportApi.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/ReportRequest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/req/TaskReport.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ReportResponse.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/Task.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/api/ReportController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliterator.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/Agent.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/AgentMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskCommand.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessor.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/TaskScheduler.java
  server/controller/src/main/resources/mapper/AgentMapper.xml
  server/pom.xml
Labels: refactor

#46 pipeline and data loader sdk
  .gitignore
  client/requirements.txt
  client/setup.py
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/starwhale/api/model.py
  client/starwhale/cli/dataset.py
  client/starwhale/utils/log.py
  example/mnist/Makefile
  example/mnist/dataset.yaml
  example/mnist/mnist/ppl.py
  example/mnist/test/swds_fuse.json
  example/mnist/test/swds_fuse_simple.json
  example/mnist/test/swds_s3.json
  example/mnist/test/swds_s3_simple.json
Labels: feature, refactor, size/l

#52 task result collection/ refactor task status/
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/resulting/EvaluationResult.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/StagingTaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskCommand.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskStatusStage.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CollectorFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/Indicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveCollectorFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsbi/BCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsbi/BCConfusionMetricsIndicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/CohenKappa.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MBCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCIndicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/TaskScheduler.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestCohenKappa.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMBCConfusionMetrics.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMCConfusionMetrics.java
Labels: feature, refactor

#53 add name into _manifest.yaml
  client/starwhale/swds/dataset.py
  client/starwhale/swmp/model.py
Labels: chores, size/s

#55 use memoryview to tune split performance
  client/starwhale/api/_impl/loader.py
  example/mnist/test/swds_s3_simple.json
Labels: enhancement

#58 add swmp ppl cmd
  client/README.md
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/model.py
  client/starwhale/consts/env.py
  client/starwhale/swds/dataset.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/load.py
  example/mnist/Makefile
  example/mnist/mnist/ppl.py
  example/mnist/model.yaml
  example/mnist/test/swds_fuse.json
  example/mnist/test/swds_s3_smoke.json
Labels: feature, refactor, size/m

#61 fix swmp delete cannot work and run twice
  client/starwhale/swmp/store.py
Labels: bug

#60 add label handle method for PipelineHandler
  client/starwhale/api/_impl/model.py
  example/mnist/mnist/ppl.py
Labels: enhancement, feature, size/s

#62 swmp upload/ swds upload/ result collector update
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadHeader.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadPhase.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/upload/UploadResult.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/Manifest.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWProcessException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/StarWhaleApiException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/api/StarWhaleApiException.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/InferenceResult.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollector.java
  server/controller/src/main/resources/mapper/SWDatasetMapper.xml
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
  server/controller/src/main/resources/sql/schema.sql
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
Labels: feature

#64 fix client setup script for pypi
  .gitignore
  client/Makefile
  client/requirements.txt
  client/setup.py
Labels: bug

#66 add spring bean configuration
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/StarWhaleControllerApplication.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageConfig.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/bean/StorageProperties.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/json/ObjectMapperConfig.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlockSerializer.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveCollectorFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollectorFactory.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
  server/controller/src/main/resources/application.yaml
  server/pom.xml
Labels: enhancement

#68 clear todos
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Init2PreparingAction.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/StagingTaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskCommand.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/user/User.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWAuthException.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleTaskScheduler.java
  server/controller/src/main/resources/mapper/JobMapper.xml
  server/controller/src/main/resources/mapper/TaskMapper.xml
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
Labels: refactor

#82 add pause job & adjust agent protocol
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackage.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
Labels: bug, enhancement, refactor

#83 fix swds/swmp/login client for stable controller api
  client/starwhale/base/store.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/mngt/user.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/http.py
  example/mnist/dataset.yaml
Labels: bug, enhancement

#86 allow swds upload duplicate version during uploading phase
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/ClientSWMPRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/common/util/Blake2bUtil.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/HotSwdsHolder.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/Manifest.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SWDSVersionWithMeta.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SWDSVersionWithMetaConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/VersionMeta.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWAuthException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWProcessException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/resources/application.yaml
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
  server/controller/src/main/resources/sql/schema.sql
  server/pom.xml
Labels: enhancement

#70 docker entrypoint for ppl
  client/requirements.txt
  client/scripts/sw-docker-entrypoint
  client/setup.py
  client/starwhale/base/store.py
  client/starwhale/cli/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/swmp/templates/entrypoint.sh
  client/starwhale/utils/__init__.py
  client/starwhale/utils/fs.py
  client/starwhale/utils/process.py
  client/starwhale/utils/venv.py
  docker/Dockerfile.base
  docker/Dockerfile.sw
  docker/Makefile
  docker/external/pip.conf
  example/mnist/requirements.txt
Labels: feature, size/l

#96 refactor result collector/ fix test issue
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/Job.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/job/JobRuntime.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSDataLocation.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndex.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackage.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/resulting/EvaluationResult.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StoragePathCoordinator.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/Agent.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/StagingTaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CollectorFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveCollectorFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveResultingPPLFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/InferenceResult.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/MCResultCollectorFactory.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/CohenKappa.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MBCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MCIndicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/MCResultingPPL.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/McDataResultCalculator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/McIndicatorReducer.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/McIndicatorRepo.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/McJobResultCalculator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/DataResultCalculator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/JobResultAggregator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/JobResultCalculator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/ResultingPPL.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/ResultingPPLFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/TaskResultAggregator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/repo/IndicatorRepo.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/repo/ObjectStorageIndicatorRepo.java
  server/controller/src/main/resources/application.yaml
  server/controller/src/test/java/ai/starwhale/test/resulting/TestCohenKappa.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMBCConfusionMetrics.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMCConfusionMetrics.java
Labels: refactor

#98 add taskset dockerfile for dind
  docker/Dockerfile.base
  docker/Dockerfile.taskset
  docker/Makefile
  docker/external/dind-dockerd-entrypoint.sh
  docker/external/docker_daemon.json
Labels: feature, size/s

#101 chores: components of static indicators/error/async load
  console/package.json
  console/public/index.html
  console/src/components/BusyLoaderWrapper/BusyLoaderWrapper.scss
  console/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx
  console/src/components/Header/index.tsx
  console/src/components/Indicator/MBCConfusionMetricsIndicator.scss
  console/src/components/Indicator/MBCConfusionMetricsIndicator.tsx
  console/src/components/Indicator/PlotlyVisualizer.scss
  console/src/components/Indicator/PlotlyVisualizer.tsx
  console/src/components/Indicator/types.d.ts
  console/src/domain/job/schemas/agent.tsx
  console/src/domain/job/schemas/task.tsx
  console/src/domain/job/services/job.ts
  console/src/i18n/locales.ts
  console/src/pages/BaseLayout.tsx
  console/src/pages/Job/JobLayout.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobResult.tsx
  console/src/pages/Job/Overview.tsx
  console/src/pages/Job/TaskLayout.tsx
  console/src/pages/Job/TaskListCard.tsx
  console/src/routes.tsx
  console/src/setupProxy.js
  console/yarn.lock
Labels: enhancement, chores, size/m

#102 fix test issue
  server/controller/src/main/java/ai/starwhale/mlops/configuration/schedule/ScheduleConfig.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/NaiveResultingPPLFinder.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/CohenKappa.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MBCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/metrics/MCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/impl/clsmulti/ppl/MCResultingPPL.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/pipline/ResultingPPL.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskStatusMachine.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageObjectInfo.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
Labels: bug

#105 split giant batch jobs
  server/controller/src/main/java/ai/starwhale/mlops/common/util/BatchOperateHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/test/java/ai/starwhale/test/common/BatchOperateHelperTest.java
Labels: bug

#106 add taskset kubernetes yaml
  docker/charts/agent.yaml
  docker/charts/namespace.yaml
Labels: feature

#108 add cpu daemonset
  docker/charts/agent.yaml
Labels: chores, size/s

#118 fix test issue
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/resources/mapper/JobMapper.xml
  server/controller/src/main/resources/mapper/TaskMapper.xml
  server/controller/src/main/resources/sql/schema.sql
Labels: bug

#119 use multipart to upload swds/swmp
  client/requirements.txt
  client/setup.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/http.py
Labels: enhancement, size/s

#126 enhanced: job result with new api & ui optimize
  console/package.json
  console/src/api/index.ts
  console/src/components/BusyLoaderWrapper/BusyLoaderWrapper.scss
  console/src/components/BusyLoaderWrapper/BusyLoaderWrapper.tsx
  console/src/components/BusyLoaderWrapper/BusyPlaceholder.tsx
  console/src/components/Card/index.tsx
  console/src/components/Header/HeaderLeftMenu.tsx
  console/src/components/Header/Logo.tsx
  console/src/components/Header/index.tsx
  console/src/components/Indicator/LabelsIndicator.tsx
  console/src/components/Indicator/PlotlyVisualizer.scss
  console/src/components/Indicator/types.d.ts
  console/src/components/Indicator/utils.ts
  console/src/components/Table/index.tsx
  console/src/domain/base/schemas/list.tsx
  console/src/domain/dataset/components/DatasetSelector.tsx
  console/src/domain/dataset/components/DatasetVersionSelector.tsx
  console/src/domain/dataset/hooks/useFetchDatasetVersions.ts
  console/src/domain/dataset/hooks/useFetchDatasets.ts
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/job/hooks/useFetchJobs.ts
  console/src/domain/job/hooks/useFetchTasks.ts
  console/src/domain/job/schemas/job.tsx
  console/src/domain/job/schemas/task.tsx
  console/src/domain/job/services/job.ts
  console/src/domain/model/components/ModelSelector.tsx
  console/src/domain/model/components/ModelVersionSelector.tsx
  console/src/domain/model/hooks/useFetchModelVersions.ts
  console/src/domain/model/hooks/useFetchModels.ts
  console/src/domain/runtime/components/BaseImageSelector.tsx
  console/src/domain/runtime/components/DeviceSelector.tsx
  console/src/domain/runtime/services/runtime.ts
  console/src/domain/user/services/user.ts
  console/src/hooks/usePage.ts
  console/src/hooks/window/useAnimationFrame.ts
  console/src/hooks/window/useResizeObserver.ts
  console/src/hooks/window/useWindowResize.ts
  console/src/i18n/locales.ts
  console/src/index.css
  console/src/pages/BaseLayout.tsx
  console/src/pages/BaseSubLayout.tsx
  console/src/pages/Dataset/DatasetListCard.tsx
  console/src/pages/Dataset/DatasetVersionListCard.tsx
  console/src/pages/Job/JobLayout.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobResult.tsx
  console/src/pages/Job/TaskLayout.tsx
  console/src/pages/Job/TaskListCard.tsx
  console/src/pages/Model/ModelListCard.tsx
  console/src/pages/Model/ModelVersionListCard.tsx
  console/src/pages/Project/Overview.tsx
  console/src/pages/Project/ProjectListCard.tsx
  console/src/routes.tsx
  console/src/theme/index.ts
  console/yarn.lock
Labels: enhancement, hotfix, size/m

#130 refactor task status : add unit test & fix unit test issue
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SWTaskScheduler.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
  server/controller/src/main/resources/application.yaml
  server/controller/src/main/resources/mapper/TaskMapper.xml
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskCache.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskStatusRequirement.java
Labels: bug

#135 add queue ability to AgentMocker & bug fix
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportedTask.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskCache.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java
Labels: bug, refactor

#141 release starwhale cli 0.1.0.dev12
  client/setup.py
  client/starwhale/utils/venv.py
  docker/Makefile
  example/mnist/requirements.txt
Labels: chores, size/s

#131 helm chart for agent
  .gitignore
  docker/Makefile
  docker/README.md
  docker/chart/.helmignore
  docker/chart/Chart.lock
  docker/chart/Chart.yaml
  docker/chart/README.md
  docker/chart/charts/common-1.13.0.tgz
  docker/chart/charts/minio-11.2.13.tgz
  docker/chart/charts/mysql-8.9.2.tgz
  docker/chart/logo.png
  docker/chart/templates/NOTES.txt
  docker/chart/templates/_helpers.tpl
  docker/chart/templates/controller-deployment.yaml
  docker/chart/templates/controller-ingress.yaml
  docker/chart/templates/daemonset.yaml
  docker/chart/templates/pv.yaml
  docker/chart/templates/serviceaccount.yaml
  docker/chart/templates/tests/test-connection.yaml
  docker/chart/values.yaml
  docker/charts/agent.yaml
  docker/charts/controller.yaml
  docker/charts/namespace.yaml
  docker/dev/nginx-chart-value.yaml
  docker/dev/pv.yaml
Labels: feature, size/l

#143 upgrade new base image and remove aliyun pypi mirror
  docker/Makefile
  docker/external/pip.conf
Labels: hotfix, size/s

#146 helm charts upgrade for versions
  docker/chart/templates/_helpers.tpl
  docker/chart/templates/controller-deployment.yaml
  docker/chart/values.yaml
Labels: enhancement, size/s

#147 use _manifest runtime as the first class runtime for python
  client/scripts/sw-docker-entrypoint
Labels: bug, size/s

#149 release starwhale cli to 0.1.0.dev13
  client/setup.py
  docker/Makefile
  example/mnist/requirements.txt
Labels: size/l, release

#152 optimize: optimize ui flow / add meta view drawer
  console/package.json
  console/src/components/Header/index.tsx
  console/src/components/Table/index.tsx
  console/src/domain/dataset/hooks/useFetchDatasetVersions.ts
  console/src/domain/dataset/schemas/datasetVersion.tsx
  console/src/domain/dataset/services/datasetVersion.ts
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/job/schemas/job.tsx
  console/src/i18n/locales.ts
  console/src/pages/Dataset/DatasetVersionListCard.tsx
  console/src/pages/Home/Login.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobResult.tsx
  console/src/pages/Job/Overview.tsx
  console/src/pages/Model/ModelVersionListCard.tsx
  console/src/pages/Project/ProjectListCard.tsx
  console/src/pages/Project/ProjectSidebar.tsx
  console/yarn.lock
Labels: enhancement, feature, size/s

#150 fix runtime parse and upgrade cli version
  client/Makefile
  client/scripts/sw-docker-entrypoint
  client/setup.py
  docker/Makefile
  example/mnist/requirements.txt
Labels: bug, size/s, release

#154 fill job finished time & fix agent time zone bug
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/Agent.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/AgentMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
  server/controller/src/main/resources/mapper/JobMapper.xml
Labels: bug, feature

#157 tune pypi and condarc config for speed
  client/Makefile
  client/requirements-dev.txt
  client/scripts/sw-docker-entrypoint
  client/setup.py
  docker/Makefile
  docker/chart/templates/_helpers.tpl
  docker/chart/templates/controller-deployment.yaml
  docker/chart/values.yaml
  docker/external/condarc
  example/mnist/requirements.txt
Labels: enhancement, release

#159 enhance: job ui refactor, fix pagination error
  console/src/components/BaseNavTabs.tsx
  console/src/components/BusyLoaderWrapper/BusyPlaceholder.tsx
  console/src/domain/base/schemas/list.tsx
  console/src/hooks/usePage.ts
  console/src/i18n/locales.ts
  console/src/pages/BaseSubLayout.tsx
  console/src/pages/Dataset/DatasetListCard.tsx
  console/src/pages/Dataset/DatasetVersionListCard.tsx
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobOverview.tsx
  console/src/pages/Job/JobResult.tsx
  console/src/pages/Job/TaskLayout.tsx
  console/src/pages/Job/TaskListCard.tsx
  console/src/pages/Model/ModelListCard.tsx
  console/src/pages/Model/ModelVersionListCard.tsx
  console/src/pages/Project/ProjectListCard.tsx
  console/src/routes.tsx
Labels: enhancement, refactor, size/s

#158 offline log api & task status loss bug fix
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ResultPath.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
  server/controller/src/main/java/ai/starwhale/mlops/api/LogApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/LogController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/Agent.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/ResultPathConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/TaskBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/schedule/TestCommandingTasksChecker.java
Labels: bug, feature

#161 enhance: datetime by browser timezone
  console/package.json
  console/src/components/BusyLoaderWrapper/BusyPlaceholder.tsx
  console/src/pages/BaseSubLayout.tsx
  console/src/utils/datetime.ts
  console/yarn.lock
Labels: enhancement, size/s

#162 feat/support demo lazylog for task logs
  console/package.json
  console/src/i18n/locales.ts
  console/src/pages/Job/JobOverview.tsx
  console/src/pages/Job/TaskListCard.tsx
  console/src/routes.tsx
  console/yarn.lock
Labels: enhancement, size/s

#164 tune helm chart for minikube
  docker/chart/templates/NOTES.txt
  docker/chart/templates/controller-deployment.yaml
  docker/chart/templates/controller-ingress.yaml
  docker/chart/values.yaml
Labels: enhancement

#166 fix charts buckets typo
  docker/chart/templates/_helpers.tpl
Labels: hotfix, size/s

#169 support multiple agent mocker
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMockerRunner.java
Labels: enhancement

#171 fix result dir bug
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/ResultPath.java
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
Labels: bug

#173 add param declaration
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/AgentMapper.java
Labels: bug
