Repository star-whale/starwhale, pull requests merged in 2022-03, with the labels that each got.

#5 init client and config code skeleton
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/doc.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  Makefile
  client/Makefile
  client/README.md
  client/requirements.txt
  client/setup.py
  client/starwhale/__init__.py
  client/starwhale/cli/__init__.py
  client/tests/__init__.py
  code-of-conduct.md
  docker/.dockerignore
  docker/Dockerfile
  docs/README.md
  docs/changelog.md
  scripts/ci.sh
  scripts/release.sh
Labels: enhancement

#11 fix:change default jdk to 8
  server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtTokenFilter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/user/UserService.java
  server/pom.xml
Labels: enhancement

#13 fix:change default jdk to 11
  server/pom.xml
Labels: enhancement

#16 feat:develop base code of agent
  server/agent/pom.xml
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/ContainerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/report/ReportHttpClient.java
  server/controller-sdk/pom.xml
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/ReportApi.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/node/Device.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/node/DeviceHolder.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/node/Node.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportRequest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportResponse.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/SWDataSet.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/SWDataSetSlice.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackage.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/Task.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/TaskTrigger.java
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/api/LoginController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/ReportController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/Code.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/agent/ReportingRequest.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/agent/ReportingResponse.java
  server/controller/src/main/java/ai/starwhale/mlops/common/ResponseFactory.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobRuntime.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/StarWhaleApiException.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/JobScheduler.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleJobScheduler.java
  server/controller/src/test/java/ai/starwhale/test/job/TestSimpleJobSpliter.java
  server/pom.xml
Labels: feature

#8 starwhale model package build cmd
  .gitignore
  client/README.md
  client/requirements.txt
  client/setup.py
  client/starwhale/__init__.py
  client/starwhale/__main__.py
  client/starwhale/api/__init__.py
  client/starwhale/cli/__init__.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/model.py
  client/starwhale/cli/predictor.py
  client/starwhale/consts/__init__.py
  client/starwhale/mngt/__init__.py
  client/starwhale/swds/__init__.py
  client/starwhale/swmp/__init__.py
  client/starwhale/swmp/docker.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/templates/Dockerfile
  client/starwhale/swmp/templates/entrypoint.sh
  client/starwhale/utils/__init__.py
  client/starwhale/utils/config.py
  client/starwhale/utils/debug.py
  client/starwhale/utils/error.py
  client/starwhale/utils/fs.py
  client/starwhale/utils/obj.py
  client/starwhale/utils/venv.py
  example/mnist/Makefile
  example/mnist/config/__init__.py
  example/mnist/config/config.py
  example/mnist/does-not-copy-file.txt
  example/mnist/hyperparam.json
  example/mnist/mnist.pkl
  example/mnist/model.yaml
  example/mnist/ppl.py
  example/mnist/requirements.txt
Labels: feature

#18 Add swmp model list/info cmd
  client/requirements.txt
  client/starwhale/cli/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
Labels: feature

#19 add login/logout cmd
  client/starwhale/cli/__init__.py
  client/starwhale/cli/mngt.py
  client/starwhale/mngt/user.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/config.py
Labels: feature

#20 add swmp pull/push/del cli
  client/starwhale/cli/__init__.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/mngt/user.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/debug.py
Labels: feature

#23 Feat agent taskexecute
  server/agent/pom.xml
  server/agent/src/main/java/ai/starwhale/mlops/agent/StarWhaleAgentApplication.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/ContainerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/exception/AllocationException.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/report/ReportHttpClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/AgentProperties.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/SourcePool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskExecutor.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskSource.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/initializer/TaskPoolInitializer.java
  server/agent/src/main/resources/application.yaml
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportResponse.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Device.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/EvaluationTask.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/common/util/ArrayHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobSpliter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/SimpleJobSpliter.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/JobScheduler.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleJobScheduler.java
  server/controller/src/test/java/ai/starwhale/test/job/TestSimpleJobSpliter.java
Labels: feature

#22 evaluation metrics implementation: Confusion Metrics/ CohenKappa
  server/controller/src/main/java/ai/starwhale/mlops/configuration/CommonExceptionHandler.java
  server/controller/src/main/java/ai/starwhale/mlops/configuration/json/DecimalJsonSerializer.java
  server/controller/src/main/java/ai/starwhale/mlops/exception/SWValidationException.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/Indicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/ResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsbi/BCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/CohenKappa.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/MBCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/MCConfusionMetrics.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/MCIndicator.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/MCResultCollector.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleJobScheduler.java
  server/controller/src/test/java/ai/starwhale/test/job/TestSimpleJobSpliter.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestCohenKappa.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMBCConfusionMetrics.java
  server/controller/src/test/java/ai/starwhale/test/resulting/TestMCConfusionMetrics.java
Labels: feature, chores

#24 add mnist to swds script
  .gitignore
  client/requirements.txt
  example/mnist/process.py
Labels: feature

#27 WIP:Feat-agent task report
  server/agent/pom.xml
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/DockerConfiguration.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskExecutor.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/taskexecutor/TaskSource.java
  server/agent/src/main/resources/docker-java.properties
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportRequest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/task/Task.java
Labels: feature

#25 add swds cli and sdk api
  client/starwhale/api/_impl/__init__.py
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/model.py
  client/starwhale/api/dataset.py
  client/starwhale/api/model.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/swds/dataset.py
  client/starwhale/swmp/model.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/fs.py
  client/starwhale/utils/venv.py
  example/mnist/dataset.yaml
  example/mnist/process.py
  example/mnist/requirements.txt
Labels: enhancement, feature

#38 add swds push cmd
  client/starwhale/swds/store.py
  client/starwhale/swmp/store.py
Labels: feature

#39 s3 storage implementation/ index loading/ task & job status management/
  server/agent/pom.xml
  server/controller-sdk/pom.xml
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndex.java
  server/controller/pom.xml
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/Job.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobSpliterator.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliterator.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskStatusMachineImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/clsmulti/MCResultCollector.java
  server/pom.xml
  server/storage-access-layer/pom.xml
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/StorageAccessService.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/S3Config.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
Labels: feature

#40 Agent docker gpu test
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/DockerConfiguration.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/NodeConfiguration.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/node/SourcePool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/GPUInfo.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/node/gpu/NvidiaDetect.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/EvaluationTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/Scheduler.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/TaskPool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/Context.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/init/RebuildTasksAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/AbsBaseTaskTransition.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/FinishedOrCanceled2ArchivedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/MonitorRunningTaskAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Preparing2RunningAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/normal/Uploading2FinishedAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/action/report/ReportAction.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/executor/TaskExecutor.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/initializer/TaskPoolInitializer.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/FileSystemTaskPersistence.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/persistence/TaskPersistence.java
  server/agent/src/main/resources/application.yaml
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/ResponseMessage.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/ReportResponse.java
Labels: enhancement, refactor

#43 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: doc

#44 add placeholder doc for contributing
  CONTRIBUTING.md
Labels: doc
