Repository star-whale/starwhale, pull requests merged in 2022-05, with the labels that each got.

#179 fix: #issue:178 update job result path with task path
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
  server/controller/src/main/resources/mapper/JobMapper.xml
Labels: bug

#183 feat: #issue:182 agent uniqueness change & #issue:180 add controller version
  server/controller-sdk/src/main/java/ai/starwhale/mlops/domain/node/Node.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/AgentEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/StatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/SystemService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/Agent.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/mapper/AgentMapper.java
  server/controller/src/main/resources/application.yaml
  server/controller/src/main/resources/db/migration/V00003__modify_agent.sql
  server/controller/src/main/resources/mapper/AgentMapper.xml
  server/controller/src/main/resources/mapper/TaskMapper.xml
  server/controller/src/main/resources/sql/schema.sql
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/schedule/TestCommandingTasksChecker.java
Labels: enhancement

#177 cli cmd for controller
  client/starwhale/base/store.py
  client/starwhale/cli/__init__.py
  client/starwhale/cli/cluster.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/predictor.py
  client/starwhale/cli/project.py
  client/starwhale/cluster/__init__.py
  client/starwhale/cluster/model.py
  client/starwhale/cluster/view.py
  client/starwhale/consts/__init__.py
  client/starwhale/mngt/user.py
  client/starwhale/project/__init__.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/config.py
  client/starwhale/utils/http.py
  server/controller-sdk/bin/.project
  server/controller-sdk/bin/.settings/org.eclipse.core.resources.prefs
  server/controller-sdk/bin/.settings/org.eclipse.m2e.core.prefs
  server/controller-sdk/bin/pom.xml
Labels: enhancement, feature, size/l

#185 add user information in login response
  server/controller/src/main/java/ai/starwhale/mlops/configuration/security/JwtLoginSuccessHandler.java
Labels: enhancement

#187 sql error fix
  server/controller/src/main/resources/mapper/AgentMapper.xml
Labels: bug

#189 tune some github issue and readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/doc.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  README.md
  docs/src/_static/img/logo_288x288px.png
  docs/src/_static/img/logo_36x36px.png
  docs/src/_static/img/logo_72x72px.png
  docs/src/_static/img/starwhale.png
Labels: doc, size/s

#190 Enhancement & Bug in issue #186
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/project/ProjectVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/DatasetVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/DatasetVersionVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swmp/SWModelPackageVersionVO.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/task/TaskVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDSVersionConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPVersionConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskConvertor.java
Labels: bug, enhancement

#200 Enhancement: get the file list by model version id
  server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SystemController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/UserController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWMPObject.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/mapper/SWModelPackageVersionMapper.java
  server/controller/src/main/resources/mapper/ProjectMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
  server/controller/src/test/java/ai/starwhale/test/login/TestPasswordEncoder.java
Labels: enhancement

#259 enhance: tune log verbose output
  client/starwhale/cli/__init__.py
  client/starwhale/cluster/model.py
  client/starwhale/consts/__init__.py
  client/starwhale/swds/dataset.py
  client/starwhale/swmp/model.py
  client/starwhale/utils/debug.py
  client/starwhale/utils/progress.py
  client/starwhale/utils/venv.py
Labels: enhancement, size/m

#264 add dataset name in swds input.json
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/InferenceTask.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/persistence/FileSystemTaskPersistence.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/SWDSBlockVO.java
  server/controller-sdk/src/main/java/ai/starwhale/mlops/api/protocol/report/resp/TaskTrigger.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/bo/JobBoConverter.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/split/JobSpliteratorByIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDataSet.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetVersionEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlock.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSBlockSerializer.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndex.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/index/SWDSIndexLoaderImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/ppl/PPLRequest.java
  server/controller/src/main/resources/mapper/JobSWDSVersionMapper.xml
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
Labels: feature

#260 bug: fix multilabel word typo
  client/starwhale/api/_impl/metric.py
  client/starwhale/cluster/view.py
  console/src/components/Indicator/types.d.ts
  console/src/pages/Job/JobResult.tsx
Labels: size/s, typo

#267 feat: add eval run local cmd
  client/scripts/sw-docker-entrypoint
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/starwhale/base/store.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/model.py
  client/starwhale/cluster/view.py
  client/starwhale/consts/__init__.py
  client/starwhale/eval/__init__.py
  client/starwhale/eval/executor.py
  client/starwhale/eval/store.py
  client/starwhale/swds/dataset.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/swmp/templates/Dockerfile
  client/starwhale/utils/__init__.py
  client/starwhale/utils/error.py
  client/starwhale/utils/progress.py
  docker/Makefile
Labels: feature, size/l

#281 chores: wrong job actions / add ico
  console/public/favicon.ico
  console/public/favicon_white.ico
  console/src/components/Indicator/LabelsIndicator.tsx
  console/src/hooks/useWebSocket.ts
  console/src/i18n/locales.ts
  console/src/pages/Job/JobListCard.tsx
  console/src/pages/Job/JobOverview.tsx
Labels: chores

#283 feat: add eval local command for list/inspect/delete
  client/starwhale/api/_impl/model.py
  client/starwhale/base/store.py
  client/starwhale/cli/eval.py
  client/starwhale/cluster/view.py
  client/starwhale/consts/__init__.py
  client/starwhale/eval/executor.py
  client/starwhale/eval/store.py
  client/starwhale/swds/store.py
  client/starwhale/utils/config.py
  client/starwhale/utils/ui.py
Labels: feature, size/m

#291 ci: add python ci
  .github/file-filter.yml
  .github/workflows/client.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/console.yml
  .github/workflows/maven-build.yml
  client/Makefile
  client/requirements-dev.txt
Labels: size/l, ci

#297 bug: fix empty exception for swmp/swds list
  client/starwhale/base/store.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/store.py
Labels: bug, size/s

#288 enhance: use extracted manifest for swmp list
  client/starwhale/swmp/store.py
Labels: enhancement, size/s

#299 ci: config black format checker
  .github/workflows/client.yaml
  client/Makefile
  client/pyproject.toml
  client/setup.py
  client/starwhale/__init__.py
  client/starwhale/__main__.py
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/metric.py
  client/starwhale/api/_impl/model.py
  client/starwhale/api/dataset.py
  client/starwhale/api/metric.py
  client/starwhale/api/model.py
  client/starwhale/base/store.py
  client/starwhale/cli/__init__.py
  client/starwhale/cli/cluster.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/mngt.py
  client/starwhale/cli/model.py
  client/starwhale/cli/project.py
  client/starwhale/cluster/__init__.py
  client/starwhale/cluster/model.py
  client/starwhale/cluster/view.py
  client/starwhale/consts/__init__.py
  client/starwhale/consts/env.py
  client/starwhale/eval/executor.py
  client/starwhale/eval/store.py
  client/starwhale/mngt/user.py
  client/starwhale/swds/dataset.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/docker.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/config.py
  client/starwhale/utils/debug.py
  client/starwhale/utils/error.py
  client/starwhale/utils/fs.py
  client/starwhale/utils/http.py
  client/starwhale/utils/load.py
  client/starwhale/utils/log.py
  client/starwhale/utils/obj.py
  client/starwhale/utils/process.py
  client/starwhale/utils/progress.py
  client/starwhale/utils/ui.py
  client/starwhale/utils/venv.py
Labels: size/l, ci

#300 chores: update readme for ci badge
  README.md
Labels: chores, size/s

#302 ci: add python flake8 lint
  client/.flake8
  client/Makefile
  client/pyproject.toml
  client/requirements.txt
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/model.py
  client/starwhale/cli/__init__.py
  client/starwhale/cluster/model.py
  client/starwhale/cluster/view.py
  client/starwhale/eval/store.py
  client/starwhale/mngt/user.py
  client/starwhale/swds/dataset.py
  client/starwhale/swmp/docker.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/debug.py
  client/starwhale/utils/error.py
  client/starwhale/utils/load.py
  client/starwhale/utils/obj.py
  client/starwhale/utils/progress.py
  client/starwhale/utils/venv.py
Labels: size/l, ci

#305 ci: add mypy type hint check
  .github/workflows/client.yaml
  client/Makefile
  client/pyproject.toml
  client/requirements-dev.txt
  client/setup.py
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/loader.py
  client/starwhale/api/_impl/metric.py
  client/starwhale/api/_impl/model.py
  client/starwhale/base/store.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/model.py
  client/starwhale/cluster/model.py
  client/starwhale/cluster/view.py
  client/starwhale/consts/__init__.py
  client/starwhale/consts/env.py
  client/starwhale/eval/executor.py
  client/starwhale/eval/store.py
  client/starwhale/swds/dataset.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/docker.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/config.py
  client/starwhale/utils/log.py
  client/starwhale/utils/process.py
Labels: size/l, ci

#306 ci: add pytest framework for client
  Makefile
  client/Makefile
  client/requirements-dev.txt
  client/tests/utils/__init__.py
  client/tests/utils/test_config.py
Labels: ci

#309 enhanced: remove client redundant requirements.txt
  client/README.md
  client/requirements.txt
Labels: enhancement, size/s, ci

#310 ci: add coverage for client
  .github/workflows/client.yaml
  .gitignore
  README.md
  client/.coveragerc
  client/.flake8
  client/Makefile
  client/requirements-dev.txt
Labels: size/m, ci

#304 ci: Ci with makefile
  .github/workflows/console.yml
  .github/workflows/maven-build.yml
  .github/workflows/release.yml
  console/Makefile
  docker/Dockerfile.controller
  docker/Dockerfile.server
  docker/Dockerfile.taskset
  docker/Makefile
  docker/chart/templates/controller-deployment.yaml
  docker/chart/values.yaml
  server/Makefile
  server/agent/pom.xml
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/LogRecorder.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskActionTest.java
  server/agent/src/test/java/ai/starwhale/mlops/agent/test/TaskExecutorTest.java
Labels: ci

#314 fix : number format error in id convertor
  server/controller/src/main/java/ai/starwhale/mlops/common/IDConvertor.java
Labels: bug

#317 fix: job typecheck error, dep upgrade
  .github/workflows/console.yml
  console/craco.config.js
  console/package.json
  console/tsconfig.base.json
  console/types/react-lazylog/LICENSE
  console/types/react-lazylog/README.md
  console/types/react-lazylog/index.d.ts
  console/types/react-lazylog/libs/LazyLog.d.ts
  console/types/react-lazylog/libs/Line.d.ts
  console/types/react-lazylog/libs/LineContent.d.ts
  console/types/react-lazylog/libs/LineNumber.d.ts
  console/types/react-lazylog/libs/LinePart.d.ts
  console/types/react-lazylog/libs/Loading.d.ts
  console/types/react-lazylog/libs/ScrollFollow.d.ts
  console/types/react-lazylog/libs/SearchBar.d.ts
  console/types/react-lazylog/package.json
  console/yarn.lock
Labels: bug

#316 ci: release pypi and refactor release image
  .github/workflows/release.yml
  client/Makefile
  client/requirements-dev.txt
  client/setup.py
  docker/Dockerfile.starwhale
  docker/Makefile
  example/mnist/requirements.txt
Labels: refactor, size/m, ci

#320 fix: adjust the sequence for build images
  .github/workflows/release.yml
  docker/Makefile
Labels: bug, chores, size/s

#321 hottfix: fix release_version env typo
  .github/workflows/release.yml
Labels: hotfix, size/s

#315 feature: add job comment
  server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobConvertor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/mapper/JobMapper.java
  server/controller/src/main/resources/db/migration/V00005__add_job_comment.sql
  server/controller/src/main/resources/mapper/JobMapper.xml
Labels: feature

#323 enhanced: refactor server image
  docker/Dockerfile.base_server
  docker/Dockerfile.server
  docker/Makefile
Labels: enhancement, size/s

#324 enhanced: always pull starwhale docker image for latest tag
  .github/workflows/client.yaml
  client/Makefile
  client/README.md
  client/starwhale/eval/executor.py
Labels: enhancement, size/s

#326 bug: fix ppl/cmp refactor bugs
  client/starwhale/api/_impl/model.py
  client/starwhale/swmp/model.py
Labels: bug, size/s

#327 hotfix: fix release yaml install typo
  .github/workflows/release.yml
Labels: hotfix, size/s

#330 feat: swcli create cmd for cluster project/job
  client/starwhale/cli/cluster.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/project.py
  client/starwhale/cluster/model.py
  client/starwhale/cluster/view.py
  client/starwhale/mngt/user.py
  client/starwhale/utils/debug.py
  client/starwhale/utils/http.py
Labels: enhancement, feature, size/m

#333 doc: add docs framework
  .github/file-filter.yml
  .github/workflows/docs.yaml
  .gitignore
  README.md
  docs/Makefile
  docs/README.md
  docs/babel.config.js
  docs/docs/faq.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/src/_static/img/starwhale.png
  docs/src/css/custom.css
  docs/src/pages/index.js
  docs/src/pages/styles.module.css
  docs/src/theme/ImageSwitcher.js
  docs/src/theme/prism-include-languages.js
  docs/src/zoom-plugin/index.js
  docs/src/zoom-plugin/zoom.js
  docs/static/.nojekyll
  docs/static/icons/ico-alert.svg
  docs/static/icons/ico-chevron-down.svg
  docs/static/icons/ico-config.svg
  docs/static/icons/ico-image.svg
  docs/static/icons/ico-info-circle.svg
  docs/static/icons/ico-open-in-new.svg
  docs/static/icons/ico-tips.svg
  docs/static/img/favicon.ico
  docs/static/img/ico-github.svg
  docs/static/img/ico-slack.svg
  docs/static/img/logo_288x288px.png
  docs/static/img/logo_36x36px.png
  docs/static/img/logo_72x72px.png
  docs/static/img/starwhale-black.png
  docs/static/img/starwhale-white.png
  docs/static/img/starwhale.png
  docs/yarn.lock
Labels: doc, size/l, ci

#334 hotfix: fix docs ci main branch typo
  .github/workflows/docs.yaml
Labels: hotfix, size/s

#336 add: e2e test of cypress
  .github/workflows/console.yml
  .gitignore
  console/cypress.json
  console/cypress/fixtures/example.json
  console/cypress/integration/sw.spec.js
  console/cypress/plugins/index.js
  console/cypress/support/commands.js
  console/cypress/support/index.js
  console/package.json
  console/yarn.lock
Labels: size/m, ci

#337 fix:agent properties bug
  server/agent/src/main/resources/application.yaml
Labels: bug

#335 chores: refactor dump pip file name
  client/starwhale/utils/venv.py
Labels: chores, size/s

#339 fix bug: Add project name verification before creating project
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
  server/controller/src/main/resources/mapper/ProjectMapper.xml
Labels: bug

#338 offer dag of task/job status view ability
  server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/dag/GraphVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGEditor.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/bo/Graph.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/bo/GraphEdge.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/bo/GraphNode.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/mapper/GraphEdgeMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/mapper/GraphMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/mapper/GraphNodeMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/po/GraphEdgeEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/po/GraphEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/po/GraphNodeEntity.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/status/JobStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/system/agent/AgentCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/LivingTaskCacheImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskWrapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/bo/Task.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperForWatch.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperReadOnly.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCacheImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskLoader.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatus.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusChangeWatcher.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/TaskStatusMachine.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/WatchableTask.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForDAG.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJob.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/resulting/CMPTaskFire.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/CommandingTasksChecker.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SWTaskScheduler.java
  server/controller/src/main/resources/db/migration/V00006__add_dag.sql
  server/controller/src/main/resources/mapper/GraphEdgeMapper.xml
  server/controller/src/main/resources/mapper/GraphMapper.xml
  server/controller/src/main/resources/mapper/GraphNodeMapper.xml
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMocker.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentMockerRunner.java
  server/controller/src/test/java/ai/starwhale/test/agent/AgentSingleRunner.java
  server/controller/src/test/java/ai/starwhale/test/domain/graph/TestGraph.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestLivingTaskCache.java
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java
  server/controller/src/test/java/ai/starwhale/test/schedule/TestCommandingTasksChecker.java
Labels: feature

#342 enhance: add model.yaml runtime check
  client/starwhale/swmp/model.py
  client/starwhale/utils/__init__.py
  client/starwhale/utils/error.py
  client/starwhale/utils/venv.py
  example/mnist/model.yaml
Labels: enhancement, size/m

#346 fix: use docker pull cmd for prepare phase
  client/starwhale/eval/executor.py
Labels: bug, size/s

#347 enhance: add sudo empty_dir cmd as the permission error fallback
  client/starwhale/swmp/store.py
  client/starwhale/utils/fs.py
  client/starwhale/utils/ui.py
Labels: enhancement, size/s

#348 fix: expose taskset port with config
  docker/Dockerfile.taskset
Labels: enhancement

#340 feat: add roc/auc for multi classification report
  client/.flake8
  client/pyproject.toml
  client/starwhale/api/_impl/metric.py
  client/starwhale/api/_impl/model.py
  example/mnist/mnist/ppl.py
  example/mnist/test/ppl_output_fuse_smoke.json
Labels: feature, size/m

#349 feat: support short name for swmp/swds/eval/dataset
  client/starwhale/base/store.py
  client/starwhale/cli/dataset.py
  client/starwhale/cli/eval.py
  client/starwhale/cli/model.py
  client/starwhale/cluster/view.py
  client/starwhale/eval/store.py
  client/starwhale/swds/dataset.py
  client/starwhale/swds/store.py
  client/starwhale/swmp/model.py
  client/starwhale/swmp/store.py
Labels: feature, size/m

#350 refactor: update for mypy disallow_untyped_calls
  client/pyproject.toml
  client/starwhale/__init__.py
  client/starwhale/api/_impl/dataset.py
  client/starwhale/api/_impl/model.py
  client/starwhale/cli/__init__.py
  client/starwhale/cli/mngt.py
  client/starwhale/cluster/model.py
  client/starwhale/mngt/user.py
  client/starwhale/utils/http.py
Labels: size/m, ci

#352 add swds pull & list for CLI
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/DatasetController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/storage/StorageService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/mapper/SWDatasetVersionMapper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/upload/SwdsUploader.java
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
Labels: feature

#351 enhance: set more reasonable s3 config for timeout and retry
  client/starwhale/api/_impl/loader.py
Labels: enhancement, size/s

#353 ci: helm charts release
  .github/file-filter.yml
  .github/workflows/helm-charts.yaml
  .github/workflows/release.yml
  .gitignore
  docker/charts/.helmignore
  docker/charts/Chart.lock
  docker/charts/Chart.yaml
  docker/charts/Makefile
  docker/charts/README.md
  docker/charts/charts/common-1.13.0.tgz
  docker/charts/charts/minio-11.2.13.tgz
  docker/charts/charts/mysql-8.9.2.tgz
  docker/charts/cr.yaml
  docker/charts/logo.png
  docker/charts/templates/NOTES.txt
  docker/charts/templates/_helpers.tpl
  docker/charts/templates/controller-deployment.yaml
  docker/charts/templates/controller-ingress.yaml
  docker/charts/templates/daemonset.yaml
  docker/charts/templates/pv.yaml
  docker/charts/templates/serviceaccount.yaml
  docker/charts/templates/tests/test-connection.yaml
  docker/charts/values.yaml
Labels: size/l, ci

#354 fix:agent error catch
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
Labels: bug

#355 fix task of fail job can't update it's status
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskJobStatusHelper.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperForWatch.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/CacheWrapperReadOnly.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/cache/LivingTaskCacheImpl.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForCache.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/status/watchers/TaskWatcherForJob.java
  server/controller/src/main/java/ai/starwhale/mlops/reporting/ReportProcessorImp.java
  server/controller/src/main/java/ai/starwhale/mlops/schedule/SimpleSWTaskScheduler.java
  server/controller/src/main/resources/db/migration/V00006__add_dag.sql
  server/controller/src/test/java/ai/starwhale/test/domain/task/TestTaskJobStatusHelper.java
Labels: bug

#357 enhance: helm refactor and readme update
  README.md
  docker/charts/Chart.yaml
  docker/charts/README.md
  docker/charts/cr.yaml
  docker/charts/logo.png
  docker/charts/templates/_helpers.tpl
  docker/charts/templates/controller-deployment.yaml
  docker/charts/values.yaml
Labels: enhancement, size/m

#358 hotfix: fix Chart.yaml version typo
  docker/charts/Chart.yaml
Labels: hotfix, size/s

#359 hotfix: fix latest default tag
  docker/charts/templates/_helpers.tpl
Labels: hotfix, size/s

#356 feat: add bootstrap
  .github/file-filter.yml
  .github/workflows/bootstrap-lint.yaml
  .gitignore
  bootstrap/.ansible-lint
  bootstrap/.pre-commit-config.yaml
  bootstrap/Makefile
  bootstrap/README.md
  bootstrap/bootstrap.yaml
  bootstrap/group_vars/all
  bootstrap/hostsDemo
  bootstrap/requirements.txt
  bootstrap/roles/agent/tasks/main.yaml
  bootstrap/roles/controller/tasks/main.yaml
  bootstrap/roles/minio/tasks/main.yaml
  bootstrap/roles/mysql/tasks/main.yaml
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/end/ArchivedAction.java
Labels: feature

#362 fix: update helm charts notes
  .github/workflows/helm-charts.yaml
  docker/charts/Makefile
  docker/charts/README.md
  docker/charts/templates/NOTES.txt
Labels: bug, enhancement, size/m

#366 Refine document text
  docs/docs/client_user_guide.md
  docs/docs/concepts.md
Labels: doc

#365 chroes: update logo icon for helm charts
  docker/charts/Chart.yaml
Labels: chores, size/s

#364 list swmp info: list all versions of swmp
  server/controller/src/main/java/ai/starwhale/mlops/api/CliApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/CliController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/swds/DatasetVO.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swds/SWDatasetService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
Labels: enhancement

#368 fix: bootstrap mount docker path
  bootstrap/roles/agent/tasks/main.yaml
  bootstrap/roles/controller/tasks/main.yaml
  bootstrap/roles/minio/tasks/main.yaml
  bootstrap/roles/mysql/tasks/main.yaml
Labels: bug

#372 chores: remove useless pre-deploy.yaml file
  .github/workflows/pre-deploy.yaml
Labels: chores, size/s

#376 fix: rename inventory file
  .gitignore
  bootstrap/Makefile
  bootstrap/inventoryDemo
Labels: enhancement

#375 fix bug: revert swds/swmp version unique index error & matching property names
  server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/protocol/job/JobRequest.java
  server/controller/src/main/resources/mapper/SWDatasetVersionMapper.xml
  server/controller/src/main/resources/mapper/SWModelPackageVersionMapper.xml
Labels: bug, invalid

#377 enhance: ui optimize & new features
  console/src/api/ApiHeader.tsx
  console/src/components/BaseSidebar.tsx
  console/src/components/Header/index.tsx
  console/src/components/IconFont/index.tsx
  console/src/components/Tag/MultiTags.tsx
  console/src/domain/dataset/services/datasetVersion.ts
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/job/schemas/job.tsx
  console/src/domain/runtime/hooks/useRuntime.ts
  console/src/domain/runtime/schemas/runtime.tsx
  console/src/domain/runtime/services/runtime.ts
  console/src/domain/setting/components/BaseImageForm.tsx
  console/src/domain/setting/hooks/useSettings.ts
  console/src/domain/setting/schemas/system.tsx
  console/src/domain/setting/services/system.ts
  console/src/i18n/locales.ts
  console/src/pages/BaseSubLayout.tsx
  console/src/pages/Dataset/DatasetListCard.tsx
  console/src/pages/Dataset/DatasetVersionListCard.tsx
  console/src/pages/Dataset/Overview.tsx
  console/src/pages/Job/JobOverviewLayout.tsx
  console/src/pages/Job/JobResults.tsx
  console/src/pages/Job/JobTasks.tsx
  console/src/pages/Model/ModelListCard.tsx
  console/src/pages/Settings/SettingAgentListCard.tsx
  console/src/pages/Settings/SettingBaseImageListCard.tsx
  console/src/pages/Settings/SettingsOverviewLayout.tsx
  console/src/pages/Settings/SettingsSidebar.tsx
  console/src/routes.tsx
  console/src/styles/_global.scss
  console/src/styles/_utils.scss
Labels: feature, size/l

#378 enhance: add docs lint and update doc index
  .github/workflows/docs.yaml
  docs/.markdownlint.yaml
  docs/Makefile
  docs/docs/client_user_guide.md
  docs/docs/concepts.md
  docs/docs/examples/mnist.md
  docs/docs/faq.md
  docs/docs/getting_started.md
  docs/docs/references/api.md
  docs/docs/references/sdk.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/yarn.lock
Labels: doc, size/m, ci

#380 chores: update field for server api changed
  client/starwhale/cluster/model.py
Labels: chores, size/l

#381 chores: change deviceCount to deviceAmount
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/job/schemas/agent.tsx
  console/src/domain/job/schemas/job.tsx
  console/src/i18n/locales.ts
  console/src/pages/Settings/SettingAgentListCard.tsx
Labels: size/s, break-change

#382 bug: fix mnist ppl typo for numpy input
  example/mnist/mnist/ppl.py
Labels: bug, size/s

#384 Feat/task block bug
  bootstrap/.pre-commit-config.yaml
  bootstrap/requirements.txt
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/AgentProperties.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/configuration/TaskConfiguration.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/ImageConfig.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/AgentTaskScheduler.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/TaskPool.java
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Init2PreparingAction.java
  server/agent/src/main/resources/application.yaml
Labels: bug

#388 chores: update default request/limit for controller cpu
  docker/charts/values.yaml
Labels: chores

#387 bug: fix push error for silent and parse name
  client/starwhale/base/store.py
  client/starwhale/swmp/store.py
  client/starwhale/utils/http.py
Labels: bug, size/s

#389 Fix/jvm oom
  docker/Dockerfile.server
Labels: bug

#390 tune swmp pull memory consumtion
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/SWModelPackageController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
Labels: enhancement

#393 fix swmp push size limited to 2G
  server/controller/src/main/java/ai/starwhale/mlops/domain/swmp/SWModelPackageService.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/LargeFileInputStream.java
  server/storage-access-layer/src/main/java/ai/starwhale/mlops/storage/s3/StorageAccessServiceS3.java
Labels: bug

#404 feat: add instance cmd
  client/pyproject.toml
  client/requirements-dev.txt
  client/starwhale/cli/__init__.py
  client/starwhale/cli/instance.py
  client/starwhale/cli/mngt.py
  client/starwhale/consts/__init__.py
  client/starwhale/instance/__init__.py
  client/starwhale/mngt/user.py
  client/starwhale/runtime/__init__.py
  client/starwhale/utils/config.py
  client/tests/utils/data/config.yaml
  client/tests/utils/test_config.py
Labels: feature, refactor, size/l

#405 enhance: highlight current instance in list
  client/starwhale/instance/__init__.py
Labels: enhancement, size/s

#410 refactor: ui components
  console/src/components/Button/index.tsx
  console/src/components/Divider.tsx
  console/src/components/Input/NumberInput.tsx
  console/src/components/Tag/MultiTags.tsx
  console/src/domain/dataset/components/DatasetForm.tsx
  console/src/domain/dataset/components/DatasetSelector.tsx
  console/src/domain/dataset/components/DatasetVersionForm.tsx
  console/src/domain/dataset/components/DatasetVersionSelector.tsx
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/model/components/ModelForm.tsx
  console/src/domain/model/components/ModelSelector.tsx
  console/src/domain/model/components/ModelVersionForm.tsx
  console/src/domain/project/components/ProjectForm.tsx
  console/src/domain/runtime/components/BaseImageSelector.tsx
  console/src/domain/runtime/components/DeviceSelector.tsx
  console/src/domain/setting/components/BaseImageForm.tsx
  console/src/hooks/useDeepEffects.ts
  console/src/pages/Home/Login.tsx
  console/src/pages/Job/JobOverviewLayout.tsx
Labels: enhancement, size/m

#412 fix bug of job list
  server/controller/src/main/java/ai/starwhale/mlops/api/EnvApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/EnvController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/EnvService.java
  server/controller/src/main/resources/mapper/JobMapper.xml
  server/controller/src/main/resources/mapper/TaskMapper.xml
Labels: bug

#411 cifar10 example
  client/starwhale/swds/dataset.py
  example/cifar10/code/__init__.py
  example/cifar10/code/data_slicer.py
  example/cifar10/code/model.py
  example/cifar10/code/ppl.py
  example/cifar10/code/test.py
  example/cifar10/code/train.py
  example/cifar10/config/__init__.py
  example/cifar10/config/config.py
  example/cifar10/config/hyperparam.json
  example/cifar10/dataset.yaml
  example/cifar10/model.yaml
  example/cifar10/models/cifar_net.pth
  example/cifar10/requirements.txt
Labels: example

#413 refactor: job summary/input/button/job create ui
  console/.eslintrc.js
  console/.storybook/preview.js
  console/package.json
  console/public/manifest.json
  console/src/components/Button/Button.tsx
  console/src/components/Button/index.tsx
  console/src/components/Indicator/SummaryIndicator.tsx
  console/src/components/Indicator/index.module.scss
  console/src/components/Input/Input.tsx
  console/src/components/Input/NumberInput.tsx
  console/src/components/Input/index.tsx
  console/src/components/Tag/MultiTags.tsx
  console/src/domain/job/components/JobForm.tsx
  console/src/domain/model/components/ModelVersionSelector.tsx
  console/src/pages/Home/Login.tsx
  console/src/pages/Job/JobResults.tsx
  console/src/stories/Button.stories.tsx
  console/src/stories/Input.stories.tsx
  console/src/styles/_utils.scss
  console/src/theme/index.ts
  console/src/utils/baseui/index.ts
  console/tsconfig.base.json
  console/yarn.lock
Labels: enhancement, size/m

#416 Feat/pip for bootstrap
  .github/workflows/bootstrap-lint.yaml
  bootstrap/.ansible-lint
  bootstrap/.flake8
  bootstrap/MANIFEST.in
  bootstrap/Makefile
  bootstrap/README.md
  bootstrap/group_vars/all
  bootstrap/inventoryDemo
  bootstrap/pyproject.toml
  bootstrap/requirements-dev.txt
  bootstrap/requirements.txt
  bootstrap/setup.py
  bootstrap/starwhale_bootstrap/__init__.py
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/deploy.py
  bootstrap/starwhale_bootstrap/playbook/bootstrap.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/agent/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/minio/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/mysql/tasks/main.yaml
Labels: feature

#423 keep playbook environment variables the same as helm uses
  bootstrap/Makefile
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  bootstrap/starwhale_bootstrap/playbook/roles/mysql/tasks/main.yaml
  docker/charts/templates/_helpers.tpl
  docker/charts/templates/controller-deployment.yaml
  docker/charts/values.yaml
  server/agent/pom.xml
  server/controller/pom.xml
Labels: optimize

#424 enhance: add env for controller
  bootstrap/starwhale_bootstrap/cmd.py
  bootstrap/starwhale_bootstrap/default.py
  bootstrap/starwhale_bootstrap/playbook/roles/controller/tasks/main.yaml
  docker/charts/templates/controller-deployment.yaml
  docker/charts/values.yaml
  server/controller/src/main/resources/application.yaml
Labels: enhancement

#417 Project recover & remove. Job log report & Job list order
  server/controller/src/main/java/ai/starwhale/mlops/api/ProjectApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/ProjectController.java
  server/controller/src/main/java/ai/starwhale/mlops/api/TaskLogWSServer.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/mapper/ProjectMapper.java
  server/controller/src/main/resources/mapper/JobMapper.xml
  server/controller/src/main/resources/mapper/ProjectMapper.xml
Labels: bug, feature

#431 fix:agent allocate devices bug
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: bug

#427 Job apis support job url(job id or uuid) instead of job id
  server/controller/src/main/java/ai/starwhale/mlops/api/JobApi.java
  server/controller/src/main/java/ai/starwhale/mlops/api/JobController.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/dag/DAGQuerier.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/job/JobService.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/Project.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/project/ProjectManager.java
  server/controller/src/main/java/ai/starwhale/mlops/domain/task/TaskService.java
Labels: enhancement

#432 fix device set bug
  server/agent/src/main/java/ai/starwhale/mlops/agent/task/inferencetask/action/normal/Preparing2RunningAction.java
Labels: bug

#433 fix device set bug
  server/agent/src/main/java/ai/starwhale/mlops/agent/container/impl/DockerContainerClient.java
Labels: bug

#434 an example of mask rcnn on PennFudanPed
  client/starwhale/swds/dataset.py
  example/PennFudanPed/code/__init__.py
  example/PennFudanPed/code/coco_eval.py
  example/PennFudanPed/code/coco_utils.py
  example/PennFudanPed/code/data_slicer.py
  example/PennFudanPed/code/ds.py
  example/PennFudanPed/code/engine.py
  example/PennFudanPed/code/model.py
  example/PennFudanPed/code/ppl.py
  example/PennFudanPed/code/test.py
  example/PennFudanPed/code/train.py
  example/PennFudanPed/code/transforms.py
  example/PennFudanPed/code/utils.py
  example/PennFudanPed/config/__init__.py
  example/PennFudanPed/config/config.py
  example/PennFudanPed/config/hyperparam.json
  example/PennFudanPed/dataset.yaml
  example/PennFudanPed/model.yaml
  example/PennFudanPed/requirements.txt
Labels: bug, example

#437 add readme for cifar10 example
  example/cifar10/README.md
  example/cifar10/doc/create.png
  example/cifar10/doc/result1.png
  example/cifar10/doc/result2.png
  example/cifar10/doc/result3.png
  example/cifar10/doc/result4.png
Labels: doc

#438 Update README.md
  example/cifar10/README.md
Labels: bug

#425 Feat/java unit coversall
  .github/workflows/maven-build.yml
  server/Makefile
  server/pom.xml
Labels: enhancement
